version: '3.7'

networks:
  ingress:
    driver: overlay
  network-data-share:
    external: true

services:
  rest-client-service:
    image: rest-client-service:1.0
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "9076:9076"
      - "5701:5701"
    networks:
      - ingress
      - network-data-share