server:
  nodeId: ${hostname:1}
  port: 9076
  accessControlAllowOrigin:
  ssl:
    enabled: false
    key-store:
    key-store-password:

healthcheck:
  maxHeapUsage: 0.8
  minDiskFreeSpace: 2147483648

data:
  lake:
    name: distributed-data-service
    url: http://distributed-data-service:9094